[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_hackathon = "Aqe7eBtusZ5D7rwKqJ64LVm9w4ZC2iPRbhX1Rqu9S3wX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
